public enum HomeScreenState
{
    MAIN,
    HOST_GAME,
    JOIN_GAME,
    GRAPH_SETTING,
    AUDIO_SETTING,
    CONTROL_SETTING,
    ACCESSIBILITY_SETTING,
    INTERFACE_SETTING,
    SYSTEM_SETTING,
    CREDITS,
    QUIT_POPUP
}
